"""init

Revision ID: 5137d77dd757
Revises: 5cdf073448f8
Create Date: 2020-08-23 15:12:01.635116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5137d77dd757'
down_revision = '5cdf073448f8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_my_model'))
    )
    op.create_index('my_index', 'my_model', ['name'], unique=True, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('my_index', table_name='my_model')
    op.drop_table('my_model')
    # ### end Alembic commands ###
