"""added settings

Revision ID: 0ad895e00ba6
Revises: ffa76280ffb3
Create Date: 2020-08-25 22:09:55.351954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad895e00ba6'
down_revision = 'ffa76280ffb3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbmgr_update_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_url', sa.Text(), nullable=True),
    sa.Column('range_from', sa.Integer(), nullable=True),
    sa.Column('range_to', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dbmgr_update_settings'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbmgr_update_settings')
    # ### end Alembic commands ###
